### ISSUE TITLE
error with live stream .m3u8 extension

### ISSUE THREAD

**Issue by muklah** [Pulimet/ExoPlayer-Wrapper#11]
Hi Dear

recently I have tried your player with live stream link which end with m3u8 extension
and the player work fine at the first but the problem is with the time counter start from 20 seconds for example then decreasing and increasing some seconds and if the internet and live stream is okay then everything still okay but if the internet being weak so sometimes the video need to keep reloading and  playing video no matter at any minutes it is
also if I pause the video for 20 seconds then play it, it still keep playing video from the moment that I paused it which lead to crashing app
so how make it keep reloading video and play it with moment that the video actually reached while it's live streaming without crashing
this is the crash that I get in logcat:

```
--------- beginning of crash
10-31 09:48:55.293 19545-19545/com.app.appa3c1907454ba E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.appa3c1907454ba, PID: 19545
    java.lang.NullPointerException: println needs a message
        at android.util.Log.println_native(Native Method)
        at android.util.Log.e(Log.java:338)
        at net.alexandroid.utils.exoplayerhelper.ExoPlayerHelper.onPlayerError(ExoPlayerHelper.java:937)
        at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:677)
        at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:129)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
you can try with this link:
https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8
and if you need a video for what happening exactly I will record one
 thanks

**Comment by Pulimet** [comment]
Hi Muklah,

I've tried to reproduce the scenario you have described but I don't get any issues.
Could you write reproducing instructions? (Based on current demo project)
Ex:
1. Make the following change in the code: ....
2. Open the app
3. Click play
4. Click pause
5. Click play
6. Here you should get the crash

Also you suggested to record the video it could be awesome in addition for instructions.

Thanks
