### ISSUE TITLE
App Crashing on MainActivity

### ISSUE THREAD

**Issue by amanbajpai** [Pulimet/ExoPlayer-Wrapper#2]
I just tried to run the updated code it crashes with a strange reason,

Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.google.android.exoplayer2.ui.SimpleExoPlayerView
                                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
                                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
                                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
                                                                                            at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                            at net.alexandroid.utils.exoplayerlibrary.MainActivity.onCreate(MainActivity.java:46)
                                                                                            at android.app.Activity.performCreate(Activity.java:6033)

**Comment by Pulimet** [comment]
By updated code do you mean the demo from this repo?
Android Studio version? 
Gradle plugin version?
Running on Emulator/Device?
Device/Emulator android version?

**Comment by amanbajpai** [comment]
the demo from this repo.
